import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <main className="bg-slate-200 flex flex-col relative min-h-screen">
          <Navbar />
          <div className="flex-grow flex items-center justify-center">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
